/**
 * Scaffold [{pkg}/]AItest/tsconfig.json + jest.config so IDE/Jest resolve `src/…`
 * imports and pick up tests outside Nest's default src spec files under src/.
 */
import { readTextFile, writeTextFile } from "../../tauri/bridge";
import { AITEST_ROOT, aitestRootFromTarget } from "../testOutputLayout";
import { overlayRelPath } from "./paths";
import type { UnitWorkspaceManifest } from "./types";

async function pathExists(projectRoot: string, rel: string): Promise<boolean> {
  try {
    await readTextFile(projectRoot, rel);
    return true;
  } catch {
    return false;
  }
}

function joinRoot(projectRoot: string, rel: string): string {
  const base = projectRoot.replace(/[/\\]+$/, "").replace(/\\/g, "/");
  return `${base}/${rel.replace(/\\/g, "/")}`;
}

/** @deprecated use aitestRootFromTarget */
export function aitestFolderFromTarget(targetRel?: string | null): string {
  return aitestRootFromTarget(targetRel);
}

export async function discoverJestTypeRootsAbs(
  projectRoot: string,
  packagePrefix?: string | null
): Promise<string[]> {
  const pkg = (packagePrefix || "").replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
  const candidates = [
    ...(pkg ? [`${pkg}/node_modules/@types`] : []),
    "node_modules/@types",
  ];
  const found: string[] = [];
  for (const root of candidates) {
    const jestPkg = `${root}/jest/package.json`;
    const jestIndex = `${root}/jest/index.d.ts`;
    if ((await pathExists(projectRoot, jestPkg)) || (await pathExists(projectRoot, jestIndex))) {
      found.push(joinRoot(projectRoot, root));
    }
  }
  if (found.length === 0) {
    return candidates.map((r) => joinRoot(projectRoot, r));
  }
  return [...new Set(found)];
}

/**
 * Extends package tsconfig, baseUrl=package root, includes ../src so
 * `import … from 'src/todos/todos.service'` typechecks (no TS2307).
 */
export function buildAitestJestTsconfig(typeRootsAbs: string[]): string {
  return `${JSON.stringify(
    {
      extends: "../tsconfig.json",
      compilerOptions: {
        baseUrl: "..",
        rootDir: "..",
        noEmit: true,
        // Override Nest nodenext so extensionless src/… imports resolve in IDE
        module: "commonjs",
        moduleResolution: "node",
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        strict: false,
        skipLibCheck: true,
        types: ["jest", "node"],
        typeRoots: typeRootsAbs,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
      },
      include: [
        "./**/*.ts",
        "./**/*.tsx",
        "../src/**/*.ts",
        "../src/**/*.tsx",
        "../src/**/*.js",
        "../src/**/*.jsx",
      ],
    },
    null,
    2
  )}\n`;
}

/** Jest config run from package cwd (backend/): finds AItest tests + maps src/. */
export function buildAitestJestConfigJs(): string {
  return `/** Generated by AITest — run from package root (folder with package.json). */
module.exports = {
  moduleFileExtensions: ["js", "json", "ts"],
  rootDir: "..",
  testMatch: [
    "<rootDir>/AItest/**/*.test.ts",
    "<rootDir>/AItest/**/*.test.tsx",
    "<rootDir>/AItest/**/*.spec.ts",
    "<rootDir>/AItest/**/*.spec.tsx",
  ],
  transform: {
    "^.+\\\\.(t|j)sx?$": [
      "ts-jest",
      {
        tsconfig: "<rootDir>/AItest/tsconfig.json",
        isolatedModules: true,
      },
    ],
  },
  testEnvironment: "node",
  moduleNameMapper: {
    "^src/(.*)$": "<rootDir>/src/$1",
  },
};
`;
}

export async function ensureAitestJestTsconfigInWorkspace(input: {
  projectRoot: string;
  manifest: UnitWorkspaceManifest;
  targetRel?: string | null;
}): Promise<UnitWorkspaceManifest> {
  const packagePrefix = input.manifest.packagePrefix;
  const typeRoots = await discoverJestTypeRootsAbs(input.projectRoot, packagePrefix);
  const tsconfigContent = buildAitestJestTsconfig(typeRoots);
  const jestContent = buildAitestJestConfigJs();
  const aitestFolder =
    aitestRootFromTarget(input.targetRel) ||
    (packagePrefix ? `${packagePrefix}/${AITEST_ROOT}` : AITEST_ROOT);

  let files = [...input.manifest.files];
  const writes: { rel: string; content: string }[] = [
    { rel: `${aitestFolder}/tsconfig.json`, content: tsconfigContent },
    { rel: `${aitestFolder}/jest.config.cjs`, content: jestContent },
  ];

  for (const w of writes) {
    const workspaceRel = overlayRelPath(input.manifest.runId, w.rel, packagePrefix);
    await writeTextFile(input.projectRoot, workspaceRel, w.content);
    const exists = await pathExists(input.projectRoot, w.rel);
    if (!exists) {
      try {
        await writeTextFile(input.projectRoot, w.rel, w.content);
      } catch {
        /* overlay enough */
      }
    }
    files = files.filter((f) => f.targetRel !== w.rel);
    files.push({
      op: exists ? "modify" : "new",
      targetRel: w.rel,
      workspaceRel,
    });
  }

  return {
    ...input.manifest,
    files,
  };
}

export function looksLikeJestTsTest(targetRel: string, content: string): boolean {
  const rel = targetRel.replace(/\\/g, "/").toLowerCase();
  const isTs = /\.(ts|tsx|js|jsx)$/.test(rel) && !/\.d\.ts$/.test(rel);
  if (!isTs) return false;
  if (!/\.(test|spec)\.(ts|tsx|js|jsx)$/.test(rel) && !rel.includes("/unittest/")) {
    return false;
  }
  const body = content.slice(0, 4000);
  return (
    /\b(describe|beforeEach|afterEach|it|test|expect)\s*\(/.test(body) ||
    /\bjest\.(mock|fn|spyOn)\b/.test(body)
  );
}
